import { ApolloDriver, type ApolloDriverConfig } from '@nestjs/apollo';
import { Module } from '@nestjs/common';
import { GraphQLModule } from '@nestjs/graphql';
import { AnalyticsModule } from '#/analytics/analytics.module.js';
import { AnalyticsResolver } from './analytics.resolver.js';
import { complexityLimitRule, depthLimitRule, MAX_QUERY_COMPLEXITY, MAX_QUERY_DEPTH } from './query-limits.js';

/**
 * `/graphql` — read-only analytics (Phase 13). Code-first, `Query` only: nothing in the schema
 * can change data. The committed `schema.gql` is generated by `npm run graphql:schema`, and an
 * integration spec proves it equals the schema this module builds.
 *
 * - The context is `{ req, res }`, which is where every global guard finds the request
 *   (`requestOf`): the same auth, role, plan and throttling rules as REST.
 * - Depth and cost limits run at validation time, before any resolver.
 * - The landing page is off (helmet's CSP would block it anyway) and introspection follows
 *   Apollo's default: on outside production.
 * - It is not in the OpenAPI document; that describes REST.
 */
@Module({
  imports: [
    AnalyticsModule,
    GraphQLModule.forRoot<ApolloDriverConfig>({
      driver: ApolloDriver,
      path: '/graphql',
      autoSchemaFile: true,
      sortSchema: true,
      context: ({ req, res }: { req: object; res: object }) => ({ req, res }),
      validationRules: [depthLimitRule(MAX_QUERY_DEPTH), complexityLimitRule(MAX_QUERY_COMPLEXITY)],
      includeStacktraceInErrorResponses: false,
      playground: false,
    }),
  ],
  providers: [AnalyticsResolver],
})
export class GraphqlApiModule {}
