import { MigrationInterface, QueryRunner } from "typeorm";

/**
 * Generated by `migration:generate`, then hand-edited to add the partial unique
 * index on `lower(email)` for password identities, which decorators cannot
 * express (the entity declares it with `synchronize: false`, so the next
 * `migration:generate` leaves it alone rather than emitting a DROP).
 *
 * `refresh_token.familyId` is NOT NULL with no default: no refresh token can
 * exist before this migration, since nothing issued them.
 */
export class AuthCore1790189091689 implements MigrationInterface {
    name = 'AuthCore1790189091689'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "refresh_token" ADD "familyId" uuid NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_b803086815f2d539fe7a0349d1" ON "refresh_token"  ("familyId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_auth_identity_password_email" ON "auth_identity" (lower("email")) WHERE "provider" = 'password'`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."uq_auth_identity_password_email"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b803086815f2d539fe7a0349d1"`);
        await queryRunner.query(`ALTER TABLE "refresh_token" DROP COLUMN "familyId"`);
    }

}
