import { MigrationInterface, QueryRunner } from "typeorm";

/**
 * Generated by `migration:generate`. `down` first deletes `oauth_exchange` tokens
 * (short-lived, meaningless without the running app) because the enum cannot lose
 * a value that rows still use.
 */
export class OAuthIdentities1790262864492 implements MigrationInterface {
    name = 'OAuthIdentities1790262864492'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TYPE "public"."auth_token_type" ADD VALUE 'oauth_exchange'`);
        await queryRunner.query(`ALTER TABLE "auth_identity" ADD CONSTRAINT "uq_auth_identity_user_provider" UNIQUE ("userId", "provider")`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "auth_identity" DROP CONSTRAINT "uq_auth_identity_user_provider"`);
        await queryRunner.query(`DELETE FROM "auth_token" WHERE "type" = 'oauth_exchange'`);
        await queryRunner.query(`CREATE TYPE "public"."auth_token_type_old" AS ENUM('activation', 'invite', 'password_reset')`);
        await queryRunner.query(`ALTER TABLE "auth_token" ALTER COLUMN "type" TYPE "public"."auth_token_type_old" USING "type"::"text"::"public"."auth_token_type_old"`);
        await queryRunner.query(`DROP TYPE "public"."auth_token_type"`);
        await queryRunner.query(`ALTER TYPE "public"."auth_token_type_old" RENAME TO "auth_token_type"`);
    }

}
