import { MigrationInterface, QueryRunner } from "typeorm";

/**
 * Generated by `migration:generate`, then hand-edited for ONE thing: the shared
 * `subscription_plan` enum is created and dropped once (see `up`).
 */
export class BillingCore1790240568294 implements MigrationInterface {
    name = 'BillingCore1790240568294'

    public async up(queryRunner: QueryRunner): Promise<void> {
        // Shared by subscription.plan, subscription_change.{fromPlan,toPlan} and
        // invoice.plan. The generator emitted this once per column, which fails on
        // the second; created once, here, and dropped once, last, in down().
        await queryRunner.query(`CREATE TYPE "public"."subscription_plan" AS ENUM('free', 'basic', 'premium')`);
        await queryRunner.query(`CREATE TABLE "subscription" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "companyId" uuid NOT NULL, "plan" "public"."subscription_plan" NOT NULL, "currentPeriodStart" TIMESTAMP WITH TIME ZONE NOT NULL, "currentPeriodEnd" TIMESTAMP WITH TIME ZONE NOT NULL, "billingAnchorDay" integer NOT NULL, "version" integer NOT NULL, CONSTRAINT "UQ_e551738d8623ccafbc57a6e8e6d" UNIQUE ("companyId"), CONSTRAINT "PK_8c3e00ebd02103caa1174cd5d9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."invoice_status" AS ENUM('finalized')`);
        await queryRunner.query(`CREATE TABLE "invoice" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "companyId" uuid NOT NULL, "plan" "public"."subscription_plan" NOT NULL, "periodStart" TIMESTAMP WITH TIME ZONE NOT NULL, "periodEnd" TIMESTAMP WITH TIME ZONE NOT NULL, "lineItems" jsonb NOT NULL, "totalCents" integer NOT NULL, "status" "public"."invoice_status" NOT NULL DEFAULT 'finalized', "dueDate" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "UQ_cb60ef5d52834ad9213fc64e84a" UNIQUE ("companyId", "periodStart"), CONSTRAINT "PK_15d25c200d9bcd8a33f698daf18" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "seat_interval" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "companyId" uuid NOT NULL, "userId" uuid NOT NULL, "activeFrom" TIMESTAMP WITH TIME ZONE NOT NULL, "activeTo" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_e43194068e895df71473a0ac09e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f0c55fd58071335f6c6bbdd9cb" ON "seat_interval"  ("userId") `);
        await queryRunner.query(`CREATE INDEX "idx_seat_interval_company_from" ON "seat_interval"  ("companyId", "activeFrom") `);
        await queryRunner.query(`CREATE TABLE "usage_event" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "companyId" uuid NOT NULL, "fileId" uuid NOT NULL, "periodKey" text NOT NULL, CONSTRAINT "PK_797d3f1dfd307095af5e4fd8457" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_usage_event_company_period" ON "usage_event"  ("companyId", "periodKey") `);
        await queryRunner.query(`CREATE TABLE "subscription_change" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "companyId" uuid NOT NULL, "fromPlan" "public"."subscription_plan", "toPlan" "public"."subscription_plan" NOT NULL, "effectiveAt" TIMESTAMP WITH TIME ZONE NOT NULL, "prorationCents" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_eca0223c789a366bc0341398604" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_subscription_change_company_effective" ON "subscription_change"  ("companyId", "effectiveAt") `);
        await queryRunner.query(`ALTER TABLE "subscription" ADD CONSTRAINT "FK_e551738d8623ccafbc57a6e8e6d" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice" ADD CONSTRAINT "FK_78299c9ae0f0236a353338e3c8a" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seat_interval" ADD CONSTRAINT "FK_f0c55fd58071335f6c6bbdd9cbc" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription_change" ADD CONSTRAINT "FK_263d3d919a7b0c6a4ab85279ac2" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "subscription_change" DROP CONSTRAINT "FK_263d3d919a7b0c6a4ab85279ac2"`);
        await queryRunner.query(`ALTER TABLE "seat_interval" DROP CONSTRAINT "FK_f0c55fd58071335f6c6bbdd9cbc"`);
        await queryRunner.query(`ALTER TABLE "invoice" DROP CONSTRAINT "FK_78299c9ae0f0236a353338e3c8a"`);
        await queryRunner.query(`ALTER TABLE "subscription" DROP CONSTRAINT "FK_e551738d8623ccafbc57a6e8e6d"`);
        await queryRunner.query(`DROP INDEX "public"."idx_subscription_change_company_effective"`);
        await queryRunner.query(`DROP TABLE "subscription_change"`);
        await queryRunner.query(`DROP INDEX "public"."idx_usage_event_company_period"`);
        await queryRunner.query(`DROP TABLE "usage_event"`);
        await queryRunner.query(`DROP INDEX "public"."idx_seat_interval_company_from"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f0c55fd58071335f6c6bbdd9cb"`);
        await queryRunner.query(`DROP TABLE "seat_interval"`);
        await queryRunner.query(`DROP TABLE "invoice"`);
        await queryRunner.query(`DROP TYPE "public"."invoice_status"`);
        await queryRunner.query(`DROP TABLE "subscription"`);
        await queryRunner.query(`DROP TYPE "public"."subscription_plan"`);
    }

}
