import { MigrationInterface, QueryRunner } from "typeorm";

/**
 * Generated by `migration:generate`, then hand-edited in exactly two places
 * that TypeORM decorators cannot express:
 *   1. `idx_audit_log_company_created` orders `createdAt DESC` (the keyset
 *      index for `GET /audit`, newest first).
 *   2. The immutability trigger on `audit_log_entry`.
 */
export class PlatformServices1790182668122 implements MigrationInterface {
    name = 'PlatformServices1790182668122'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "audit_log_entry" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "companyId" uuid NOT NULL, "actorUserId" uuid, "action" text NOT NULL, "targetType" text, "targetId" uuid, "metadata" jsonb NOT NULL DEFAULT '{}', "ip" text, "correlationId" text, CONSTRAINT "PK_905deda75b16075725a02ef38a0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_audit_log_company_created" ON "audit_log_entry"  ("companyId", "createdAt" DESC, "id") `);
        await queryRunner.query(`CREATE FUNCTION "audit_log_entry_immutable"() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'audit_log_entry is immutable: % is not allowed', TG_OP USING ERRCODE = 'restrict_violation'; END; $$ LANGUAGE plpgsql`);
        await queryRunner.query(`CREATE TRIGGER "trg_audit_log_entry_immutable" BEFORE UPDATE OR DELETE ON "audit_log_entry" FOR EACH ROW EXECUTE FUNCTION "audit_log_entry_immutable"()`);
        await queryRunner.query(`CREATE TYPE "public"."background_task_type" AS ENUM('send_email')`);
        await queryRunner.query(`CREATE TYPE "public"."background_task_status" AS ENUM('pending', 'running', 'succeeded', 'dead')`);
        await queryRunner.query(`CREATE TABLE "background_task" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "type" "public"."background_task_type" NOT NULL, "payload" jsonb NOT NULL, "status" "public"."background_task_status" NOT NULL DEFAULT 'pending', "attempts" integer NOT NULL DEFAULT '0', "runAfter" TIMESTAMP WITH TIME ZONE NOT NULL, "lastError" text, "lockedAt" TIMESTAMP WITH TIME ZONE, "correlationId" text, CONSTRAINT "PK_f5f4188e3ad86b72672c6a75fd1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_background_task_status_run_after" ON "background_task"  ("status", "runAfter") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."idx_background_task_status_run_after"`);
        await queryRunner.query(`DROP TABLE "background_task"`);
        await queryRunner.query(`DROP TYPE "public"."background_task_status"`);
        await queryRunner.query(`DROP TYPE "public"."background_task_type"`);
        await queryRunner.query(`DROP TRIGGER "trg_audit_log_entry_immutable" ON "audit_log_entry"`);
        await queryRunner.query(`DROP FUNCTION "audit_log_entry_immutable"()`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_log_company_created"`);
        await queryRunner.query(`DROP TABLE "audit_log_entry"`);
    }

}
