import { MigrationInterface, QueryRunner } from "typeorm";

/**
 * Generated by `migration:generate`, then hand-edited:
 *
 * - The partial index `idx_file_asset_company_live` (live files only) is added; a
 *   decorator cannot express a `WHERE`.
 * - The generated drop/recreate of `idx_audit_log_company_created` is REMOVED: it
 *   would have recreated the index without its hand-made `createdAt DESC`. Postgres
 *   rebuilds an index itself when a column's type changes, keeping its definition.
 * - `usage_event` is emptied before its new foreign key. Nothing wrote usage events
 *   until this phase (the entity existed so the quota logic could be tested), so
 *   there is nothing to lose.
 * - `down` deletes `build_data_quality_report` tasks first: the enum cannot drop a
 *   value rows still use.
 *
 * `createdAt`/`updatedAt` become millisecond precision everywhere (see `BaseEntity`):
 * a keyset cursor is a JS Date, and microseconds it cannot carry make every page
 * repeat the previous page's last row.
 */
export class FilesAndIdempotency1790265133409 implements MigrationInterface {
    name = 'FilesAndIdempotency1790265133409'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."file_visibility" AS ENUM('company', 'restricted')`);
        await queryRunner.query(`CREATE TABLE "file_asset" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "createdAt" TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT now(), "companyId" uuid NOT NULL, "uploaderId" uuid NOT NULL, "originalName" text NOT NULL, "mimeType" text NOT NULL, "sizeBytes" integer NOT NULL, "storageKey" text NOT NULL, "visibility" "public"."file_visibility" NOT NULL DEFAULT 'company', "deletedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_4cc6688b434b7f95a9788fa5f4c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_file_asset_company" ON "file_asset"  ("companyId", "deletedAt", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_file_asset_company_live" ON "file_asset" ("companyId", "createdAt") WHERE "deletedAt" IS NULL`);
        await queryRunner.query(`CREATE TYPE "public"."idempotency_status" AS ENUM('in_progress', 'completed')`);
        await queryRunner.query(`CREATE TABLE "idempotency_record" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "createdAt" TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT now(), "companyId" uuid NOT NULL, "key" text NOT NULL, "route" text NOT NULL, "requestHash" text NOT NULL, "status" "public"."idempotency_status" NOT NULL DEFAULT 'in_progress', "statusCode" integer, "responseBody" jsonb, "responseHeaders" jsonb, CONSTRAINT "uq_idempotency_company_key" UNIQUE ("companyId", "key"), CONSTRAINT "PK_0dc165e218120167e4a55dcc8d4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "file_access_grant" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "createdAt" TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT now(), "fileId" uuid NOT NULL, "userId" uuid NOT NULL, CONSTRAINT "uq_file_access_grant_file_user" UNIQUE ("fileId", "userId"), CONSTRAINT "PK_cb3b70ed346318066690905cdd3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_aadc506a332b0e21ce90e4bbcf" ON "file_access_grant"  ("userId") `);
        await queryRunner.query(`ALTER TABLE "company" ALTER COLUMN "createdAt" TYPE TIMESTAMP(3) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "company" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(3) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "subscription" ALTER COLUMN "createdAt" TYPE TIMESTAMP(3) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "subscription" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(3) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "invoice" ALTER COLUMN "createdAt" TYPE TIMESTAMP(3) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "invoice" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(3) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "createdAt" TYPE TIMESTAMP(3) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(3) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "seat_interval" ALTER COLUMN "createdAt" TYPE TIMESTAMP(3) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "seat_interval" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(3) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "usage_event" ALTER COLUMN "createdAt" TYPE TIMESTAMP(3) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "usage_event" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(3) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "audit_log_entry" ALTER COLUMN "createdAt" TYPE TIMESTAMP(3) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "audit_log_entry" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(3) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "background_task" ALTER COLUMN "createdAt" TYPE TIMESTAMP(3) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "background_task" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(3) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TYPE "public"."background_task_type" ADD VALUE 'build_data_quality_report'`);
        await queryRunner.query(`ALTER TABLE "subscription_change" ALTER COLUMN "createdAt" TYPE TIMESTAMP(3) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "subscription_change" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(3) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "auth_identity" ALTER COLUMN "createdAt" TYPE TIMESTAMP(3) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "auth_identity" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(3) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "auth_token" ALTER COLUMN "createdAt" TYPE TIMESTAMP(3) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "auth_token" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(3) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "refresh_token" ALTER COLUMN "createdAt" TYPE TIMESTAMP(3) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "refresh_token" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(3) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "file_asset" ADD CONSTRAINT "FK_d78838bdadb7deb4d5b89183398" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "file_asset" ADD CONSTRAINT "FK_a5df8b673d73519ea68f33c0028" FOREIGN KEY ("uploaderId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`DELETE FROM "usage_event"`);
        await queryRunner.query(`ALTER TABLE "usage_event" ADD CONSTRAINT "FK_328a36db1c8c9dfd7367fe62398" FOREIGN KEY ("fileId") REFERENCES "file_asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "idempotency_record" ADD CONSTRAINT "FK_0a724b11908809f5eaa67ecbba3" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "file_access_grant" ADD CONSTRAINT "FK_017c24313b235dbee45b2584f68" FOREIGN KEY ("fileId") REFERENCES "file_asset"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "file_access_grant" ADD CONSTRAINT "FK_aadc506a332b0e21ce90e4bbcf1" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "file_access_grant" DROP CONSTRAINT "FK_aadc506a332b0e21ce90e4bbcf1"`);
        await queryRunner.query(`ALTER TABLE "file_access_grant" DROP CONSTRAINT "FK_017c24313b235dbee45b2584f68"`);
        await queryRunner.query(`ALTER TABLE "idempotency_record" DROP CONSTRAINT "FK_0a724b11908809f5eaa67ecbba3"`);
        await queryRunner.query(`ALTER TABLE "usage_event" DROP CONSTRAINT "FK_328a36db1c8c9dfd7367fe62398"`);
        await queryRunner.query(`ALTER TABLE "file_asset" DROP CONSTRAINT "FK_a5df8b673d73519ea68f33c0028"`);
        await queryRunner.query(`ALTER TABLE "file_asset" DROP CONSTRAINT "FK_d78838bdadb7deb4d5b89183398"`);
        await queryRunner.query(`ALTER TABLE "refresh_token" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(6) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "refresh_token" ALTER COLUMN "createdAt" TYPE TIMESTAMP(6) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "auth_token" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(6) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "auth_token" ALTER COLUMN "createdAt" TYPE TIMESTAMP(6) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "auth_identity" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(6) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "auth_identity" ALTER COLUMN "createdAt" TYPE TIMESTAMP(6) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "subscription_change" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(6) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "subscription_change" ALTER COLUMN "createdAt" TYPE TIMESTAMP(6) WITH TIME ZONE`);
        await queryRunner.query(`DELETE FROM "background_task" WHERE "type" = 'build_data_quality_report'`);
        await queryRunner.query(`CREATE TYPE "public"."background_task_type_old" AS ENUM('send_email')`);
        await queryRunner.query(`ALTER TABLE "background_task" ALTER COLUMN "type" TYPE "public"."background_task_type_old" USING "type"::"text"::"public"."background_task_type_old"`);
        await queryRunner.query(`DROP TYPE "public"."background_task_type"`);
        await queryRunner.query(`ALTER TYPE "public"."background_task_type_old" RENAME TO "background_task_type"`);
        await queryRunner.query(`ALTER TABLE "background_task" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(6) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "background_task" ALTER COLUMN "createdAt" TYPE TIMESTAMP(6) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "audit_log_entry" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(6) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "audit_log_entry" ALTER COLUMN "createdAt" TYPE TIMESTAMP(6) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "usage_event" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(6) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "usage_event" ALTER COLUMN "createdAt" TYPE TIMESTAMP(6) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "seat_interval" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(6) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "seat_interval" ALTER COLUMN "createdAt" TYPE TIMESTAMP(6) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(6) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "createdAt" TYPE TIMESTAMP(6) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "invoice" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(6) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "invoice" ALTER COLUMN "createdAt" TYPE TIMESTAMP(6) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "subscription" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(6) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "subscription" ALTER COLUMN "createdAt" TYPE TIMESTAMP(6) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "company" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(6) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "company" ALTER COLUMN "createdAt" TYPE TIMESTAMP(6) WITH TIME ZONE`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aadc506a332b0e21ce90e4bbcf"`);
        await queryRunner.query(`DROP TABLE "file_access_grant"`);
        await queryRunner.query(`DROP TABLE "idempotency_record"`);
        await queryRunner.query(`DROP TYPE "public"."idempotency_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_file_asset_company_live"`);
        await queryRunner.query(`DROP INDEX "public"."idx_file_asset_company"`);
        await queryRunner.query(`DROP TABLE "file_asset"`);
        await queryRunner.query(`DROP TYPE "public"."file_visibility"`);
    }

}
