// SCOPE.md B2 Consumers table. Every queue is declared here even before
// its consumer exists (BullMQ queues accumulate jobs safely with no
// worker attached) — but per the storefront backend plan, the outbox's
// routing table (event-routing.ts) only routes to a queue once that
// queue's consumer actually ships, so nothing silently backs up waiting
// for a future slice.
export enum QueueName {
  NOTIFICATIONS = 'notifications',
  MEDIA = 'media',
  SEARCH = 'search',
  ANALYTICS = 'analytics',
  AUDIT_LOG = 'audit-log',
  WEBHOOKS = 'webhooks',

  // Not in SCOPE.md B2's original consumers table — added in S9 for its
  // own explicit "invoice PDF generated by a queue consumer" bullet.
  // Kept separate from NOTIFICATIONS rather than folded into it: this
  // backend doesn't build the "Order confirmed" email itself (no new
  // email templates beyond S4's two are in scope here), so there's no
  // existing notifications-consumer code path to attach PDF generation
  // to — it stands alone, producing Order.invoiceUrl for the "invoice
  // download" read endpoint.
  INVOICES = 'invoices',
}
