const LOADING_QUOTES = [
  "Pinging the cloud (it's not a real cloud)...",
  "Convincing the CPU to try harder...",
  "Rebasing your expectations...",
  "Grepping for the meaning of life...",
  "Sacrificing a semicolon...",
  "Rewriting it in Rust...",
  "Yak shaving in progress...",
  "Turning it off and on again...",
  "Consulting the ancient COBOL scrolls...",
  "Herding the microservices...",
  "Untangling spaghetti code...",
  "Waiting for npm install to finish...",
  "Appeasing the linter...",
  "Rolling back a rollback...",
  "Fetching from origin/main...",
  "Committing without a message...",
  "Force-pushing to production...",
  "Debugging the debugger...",
  "Casting to any...",
  "Silencing the console.logs...",
  "Warming up the JIT compiler...",
  "Garbage collecting your patience...",
  "Spinning up a Docker container...",
  "Whispering to the load balancer...",
  "Refactoring for the fourth time...",
  "Squashing commits and bugs...",
  "Praying to the CI/CD pipeline...",
  "Restocking the stack...",
  "Deallocating unused feelings...",
  "Binary searching for answers...",
  "Caching the uncacheable...",
  "Mocking the tests (and your code)...",
  "Hashing out the details...",
  "Rendering the render...",
  "Polling for updates...",
  "Throttling the requests...",
  "Serializing the chaos...",
  "Deserializing the confusion...",
  "Instantiating a singleton (again)...",
  "Waiting on a promise...",
  "Resolving merge conflicts...",
  "Sharding the database...",
  "Indexing everything (twice)...",
  "Bypassing the CAPTCHA...",
  "Encrypting the small talk...",
  "Decrypting the fine print...",
  "Sniffing packets...",
  "Rotating the logs...",
  "Tailing the wrong file...",
  "Chmod 777-ing responsibility...",
  "Sudo-ing without asking...",
  "Piping stdout to nowhere...",
  "Killing zombie processes...",
  "Forking the repo of life...",
  "Cloning your enthusiasm...",
  "Pulling an all-nighter...",
  "Pushing technical debt...",
  "Vendoring the dependencies...",
  "Bundling the webpack...",
  "Minifying the drama...",
  "Transpiling from JS to feelings...",
  "Lazy loading your patience...",
  "Prefetching the punchline...",
  "Hydrating the server components...",
  "Tree-shaking dead weight...",
  "Polyfilling the gaps...",
  "Linting your life choices...",
  "Type-checking reality...",
  "Null-checking the void...",
  "Catching an uncaught exception...",
  "Throwing a Hail Mary exception...",
  "Awaiting async destiny...",
  "Queueing up excuses...",
  "Deploying on a Friday...",
  "Reverting the revert...",
  "Cherry-picking the good parts...",
  "Stashing unfinished business...",
  "Diffing your expectations...",
  "Blaming it on cache invalidation...",
  "Naming things (the hard part)...",
  "Counting off by one...",
];

/** A random quote, never the same as `exclude` (so rotations don't repeat back-to-back). */
export function getRandomQuote(exclude?: string): string {
  const pool = exclude
    ? LOADING_QUOTES.filter((q) => q !== exclude)
    : LOADING_QUOTES;
  
  return pool[Math.floor(Math.random() * pool.length)]!;
}
