import type { Product } from '@/app/core/models/product.model';

const IMAGE = { url: '/demo/placeholder-product.svg', alt: '' };

/**
 * Mock catalog data — this is an accessories store (SCOPE.md A8's ten
 * categories don't include clubs), so no drivers/putters/irons here,
 * unlike some earlier ad-hoc styleguide demo data that predated this
 * being the canonical fixture source.
 *
 * Products that appear in the homepage's Featured carousel use real
 * downloaded photography (public/images/products/) rather than the
 * placeholder SVG — swapped in because they're on-screen by default,
 * not deferred. `isFeatured` on p7/p8 was flipped for the same reason:
 * no real rangefinder photo was available in the source design, and a
 * placeholder in an otherwise-real carousel reads as more broken than a
 * different featured product would.
 */
export const PRODUCT_FIXTURES: Product[] = [
  {
    id: 'p1',
    slug: 'premium-leather-glove',
    name: 'Premium Leather Glove',
    brand: '3legant',
    sku: 'GLV-001',
    category: 'gloves',
    description: 'Cabretta leather glove with reinforced palm for grip in wet conditions.',
    price: 34,
    images: [{ url: '/images/products/glove-shark.jpg', alt: 'Premium Leather Glove' }],
    variants: [
      { id: 'p1-v1', sku: 'GLV-001-RM', attributes: { hand: 'left', size: 'M' }, price: 34, stock: 40 },
      { id: 'p1-v2', sku: 'GLV-001-RL', attributes: { hand: 'left', size: 'L' }, price: 34, stock: 25 },
    ],
    rating: 4.8,
    reviewCount: 52,
    isFeatured: true,
    publishedAt: '2026-01-15T00:00:00.000Z',
  },
  {
    id: 'p2',
    slug: 'tour-performance-golf-balls',
    name: 'Tour Performance Golf Balls (Dozen)',
    brand: '3legant',
    sku: 'BAL-002',
    category: 'balls',
    description: 'Three-piece urethane cover balls tuned for greenside spin.',
    price: 44.99,
    originalPrice: 49.99,
    images: [{ url: '/images/products/balls-taylormade.jpg', alt: 'Tour Performance Golf Balls' }],
    variants: [
      { id: 'p2-v1', sku: 'BAL-002-LOW', attributes: { compression: 'low' }, price: 44.99, stock: 80 },
      { id: 'p2-v2', sku: 'BAL-002-HIGH', attributes: { compression: 'high' }, price: 44.99, stock: 60 },
    ],
    rating: 4.5,
    reviewCount: 128,
    isFeatured: true,
    publishedAt: '2026-02-01T00:00:00.000Z',
  },
  {
    id: 'p3',
    slug: 'bamboo-golf-tees-100-pack',
    name: 'Bamboo Golf Tees (100-Pack)',
    brand: '3legant',
    sku: 'TEE-003',
    category: 'tees',
    description: 'Biodegradable bamboo tees, stronger than pine at the same length.',
    price: 12.99,
    images: [{ ...IMAGE, alt: 'Bamboo Golf Tees' }],
    variants: [{ id: 'p3-v1', sku: 'TEE-003-83', attributes: { packSize: 100 }, price: 12.99, stock: 200 }],
    rating: 4.6,
    reviewCount: 34,
    isFeatured: false,
    publishedAt: '2026-01-20T00:00:00.000Z',
  },
  {
    id: 'p4',
    slug: 'driver-headcover',
    name: 'Driver Headcover',
    brand: '3legant',
    sku: 'HDC-004',
    category: 'headcovers',
    description: 'Knit driver headcover with number tag.',
    price: 24.99,
    images: [{ ...IMAGE, alt: 'Driver Headcover' }],
    variants: [
      { id: 'p4-v1', sku: 'HDC-004-BLK', attributes: { colourway: 'Black' }, price: 24.99, stock: 30 },
      { id: 'p4-v2', sku: 'HDC-004-NVY', attributes: { colourway: 'Navy' }, price: 24.99, stock: 18 },
    ],
    rating: 4.3,
    reviewCount: 12,
    isFeatured: false,
    publishedAt: '2026-03-01T00:00:00.000Z',
  },
  {
    id: 'p5',
    slug: 'waffle-golf-towel',
    name: 'Waffle Golf Towel',
    brand: '3legant',
    sku: 'TWL-005',
    category: 'towels',
    description: 'Microfiber waffle-weave towel with carabiner clip.',
    price: 18.99,
    images: [{ ...IMAGE, alt: 'Waffle Golf Towel' }],
    variants: [{ id: 'p5-v1', sku: 'TWL-005', attributes: { colourway: 'White' }, price: 18.99, stock: 55 }],
    rating: 4.7,
    reviewCount: 21,
    isFeatured: false,
    publishedAt: '2026-02-10T00:00:00.000Z',
  },
  {
    id: 'p6',
    slug: 'cart-bag-14-way',
    name: 'Cart Bag 14-Way',
    brand: '3legant',
    sku: 'BAG-006',
    category: 'bags',
    description: '14-way top organizer with full-length dividers and a rain hood.',
    price: 189.99,
    originalPrice: 229.99,
    images: [{ url: '/images/products/bag-utility-rover.jpg', alt: 'Cart Bag 14-Way' }],
    variants: [
      { id: 'p6-v1', sku: 'BAG-006-BLK', attributes: { colourway: 'Black' }, price: 189.99, stock: 10 },
      { id: 'p6-v2', sku: 'BAG-006-GRN', attributes: { colourway: 'Forest Green' }, price: 189.99, stock: 6 },
    ],
    rating: 4.4,
    reviewCount: 19,
    isFeatured: true,
    publishedAt: '2026-01-05T00:00:00.000Z',
  },
  {
    id: 'p7',
    slug: 'laser-rangefinder-pro',
    name: 'Laser Rangefinder Pro',
    brand: '3legant',
    sku: 'RNG-007',
    category: 'rangefinders-gps',
    description: 'Slope-adjusted laser rangefinder with pin-lock vibration.',
    price: 249.99,
    images: [{ ...IMAGE, alt: 'Laser Rangefinder Pro' }],
    variants: [{ id: 'p7-v1', sku: 'RNG-007', attributes: {}, price: 249.99, stock: 15 }],
    rating: 4.9,
    reviewCount: 87,
    isFeatured: false,
    publishedAt: '2026-02-20T00:00:00.000Z',
  },
  {
    id: 'p8',
    slug: 'performance-polo-shirt',
    name: 'Performance Polo Shirt',
    brand: '3legant',
    sku: 'APP-008',
    category: 'apparel',
    description: 'Moisture-wicking stretch polo with UV protection.',
    price: 59.99,
    images: [{ url: '/images/products/polo-greg-norman.jpg', alt: 'Performance Polo Shirt' }],
    variants: [
      { id: 'p8-v1', sku: 'APP-008-S-WHT', attributes: { size: 'S', colourway: 'White' }, price: 59.99, stock: 20 },
      { id: 'p8-v2', sku: 'APP-008-M-WHT', attributes: { size: 'M', colourway: 'White' }, price: 59.99, stock: 28 },
      { id: 'p8-v3', sku: 'APP-008-M-NVY', attributes: { size: 'M', colourway: 'Navy' }, price: 59.99, stock: 22 },
    ],
    rating: 4.2,
    reviewCount: 15,
    isFeatured: true,
    publishedAt: '2026-03-10T00:00:00.000Z',
  },
];
