// GENERATED by design/build-tokens.mjs from design/tokens.json. Do not edit by hand.
// The transactional emails' palette (see templates.ts). Literal hex: email HTML cannot use CSS variables.
export const BRAND = {
  canvas: '#f9f3e3',
  surface: '#fefbf3',
  sunken: '#f2ebd7',
  line: '#dad0ba',
  lineStrong: '#857863',
  text: '#191610',
  textMuted: '#534c41',
  textSubtle: '#6b6254',
  cover: '#191610',
  onCover: '#f8f5eb',
  tag: '#f9cc21',
  tagSoft: '#fdefba',
  onTag: '#191610',
  pass: '#0a6d37',
  passSoft: '#d7f4dc',
  hold: '#b7191c',
  holdSoft: '#ffe9e6',
  caution: '#925019',
  cautionSoft: '#ffe9d0',
  tabOrange: '#f16a00',
  tabGrass: '#399e43',
  tabTeal: '#009a9b',
  tabBlue: '#235bc8',
  tabSienna: '#874723',
  /** Archivo where the client loads web fonts (Apple Mail, iOS, Thunderbird); Arial Narrow / Arial everywhere else. */
  fontSans: "'Archivo', Arial, Helvetica, sans-serif",
  fontHeadline: "'Archivo', 'Arial Narrow', Arial, Helvetica, sans-serif",
  fontMono: "'Martian Mono', 'Courier New', Courier, monospace",
  fontUrl:
    'https://fonts.googleapis.com/css2?family=Archivo:wdth,wght@62..125,100..900&family=Martian+Mono:wght@400..700&display=swap',
  /** The mark as a PNG on the brand-assets origin, when one is configured. */
  logoPath: '/brand/v1/logo.png',
} as const;
