// Builds every generated design file from design/tokens.json — the one source of Gridline's design language.
//   node design/build-tokens.mjs           write the generated files
//   node design/build-tokens.mjs --check   fail (exit 1) if any generated file is out of date or any contrast pair fails
// No dependencies: runs on plain Node from any working directory.
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const tokens = JSON.parse(readFileSync(join(HERE, 'tokens.json'), 'utf8'));
const check = process.argv.includes('--check');
const THEMES = ['light', 'dark'];
const HEADER = 'GENERATED by design/build-tokens.mjs from design/tokens.json. Do not edit by hand.';

// ---------- colour maths: OKLCH -> sRGB (Björn Ottosson's matrices), WCAG relative luminance ----------

function parseOklch(value) {
  const match = /^oklch\(\s*([\d.]+)\s+([\d.]+)\s+([\d.]+)\s*\)$/.exec(value);
  if (!match) throw new Error(`Not an oklch() colour: ${value}`);
  return { l: Number(match[1]), c: Number(match[2]), h: Number(match[3]) };
}

function oklchToLinearSrgb({ l, c, h }) {
  const a = c * Math.cos((h * Math.PI) / 180);
  const b = c * Math.sin((h * Math.PI) / 180);
  const l_ = (l + 0.3963377774 * a + 0.2158037573 * b) ** 3;
  const m_ = (l - 0.1055613458 * a - 0.0638541728 * b) ** 3;
  const s_ = (l - 0.0894841775 * a - 1.291485548 * b) ** 3;
  return [
    4.0767416621 * l_ - 3.3077115913 * m_ + 0.2309699292 * s_,
    -1.2684380046 * l_ + 2.6097574011 * m_ - 0.3413193965 * s_,
    -0.0041960863 * l_ - 0.7034186147 * m_ + 1.707614701 * s_,
  ].map((channel) => Math.min(1, Math.max(0, channel)));
}

const encode = (x) => (x <= 0.0031308 ? 12.92 * x : 1.055 * x ** (1 / 2.4) - 0.055);

export function oklchToHex(value) {
  return `#${oklchToLinearSrgb(parseOklch(value))
    .map((x) => Math.round(encode(x) * 255).toString(16).padStart(2, '0'))
    .join('')}`;
}

function luminance(value) {
  // WCAG uses luminance of the sRGB colour as displayed: gamut-clamp, 8-bit round, then linearise.
  const [r, g, b] = oklchToLinearSrgb(parseOklch(value)).map((x) => {
    const byte = Math.round(encode(x) * 255) / 255;
    return byte <= 0.04045 ? byte / 12.92 : ((byte + 0.055) / 1.055) ** 2.4;
  });
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

function contrast(foreground, background) {
  const [hi, lo] = [luminance(foreground), luminance(background)].sort((x, y) => y - x);
  return (hi + 0.05) / (lo + 0.05);
}

// ---------- the model ----------

const roles = Object.keys(tokens.color.light).filter((key) => !key.startsWith('$'));
for (const theme of THEMES) {
  const missing = roles.filter((role) => !tokens.color[theme][role]);
  const extra = Object.keys(tokens.color[theme]).filter((role) => !role.startsWith('$') && !roles.includes(role));
  if (missing.length || extra.length) {
    throw new Error(`Theme "${theme}" must define exactly the light roles. Missing: ${missing}. Extra: ${extra}.`);
  }
}
const colour = (theme, role) => tokens.color[theme][role].$value;
const entries = (group) => Object.entries(group).filter(([key]) => !key.startsWith('$'));

// ---------- contrast gate ----------

const MINIMUM = { text: 4.5, large: 3, ui: 3 };
const failures = [];
for (const theme of THEMES) {
  for (const [fg, bg, kind] of tokens.contrast.pairs) {
    const ratio = contrast(colour(theme, fg), colour(theme, bg));
    if (ratio < MINIMUM[kind]) failures.push(`${theme}: ${fg} on ${bg} = ${ratio.toFixed(2)} (needs ${MINIMUM[kind]} for ${kind})`);
  }
}

// ---------- outputs ----------

function tokensCss() {
  const vars = (theme) => roles.map((role) => `  --gl-${role}: ${colour(theme, role)};`).join('\n');
  const text = entries(tokens.text)
    .map(([name, t]) => `  --text-${name}: ${t.$value};\n  --text-${name}--line-height: ${t.leading};`)
    .join('\n');
  return `/* ${HEADER} */

:root,
[data-theme="light"] {
  color-scheme: light;
${vars('light')}
  --gl-shadow-overlay: ${tokens.shadow.overlay.light};
}

[data-theme="dark"] {
  color-scheme: dark;
${vars('dark')}
  --gl-shadow-overlay: ${tokens.shadow.overlay.dark};
}

@theme inline {
${roles.map((role) => `  --color-${role}: var(--gl-${role});`).join('\n')}

  --font-sans: ${tokens.font.sans.$value};
  --font-mono: ${tokens.font.mono.$value};
${entries(tokens.width).map(([name, w]) => `  --font-width-${name}: ${w.$value};`).join('\n')}

${text}

${entries(tokens.radius).map(([name, r]) => `  --radius-${name}: ${r.$value};`).join('\n')}

  --shadow-overlay: var(--gl-shadow-overlay);

${entries(tokens.motion)
  .map(([name, m]) => (name.startsWith('ease') ? `  --ease-${name.slice(5)}: ${m.$value};` : `  --duration-${name}: ${m.$value};`))
  .join('\n')}
}
`;
}

/** The mark: a box-board square ruled into four cells, one cell holding the file (manila). Same geometry as components/brand/logo.tsx. */
function iconSvg() {
  const field = oklchToHex(colour('light', 'field'));
  const rule = oklchToHex(colour('light', 'on-field'));
  const cell = oklchToHex(colour('light', 'folder'));
  return `<!-- ${HEADER} -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
  <rect width="32" height="32" rx="4" fill="${field}"/>
  <rect x="17.5" y="5" width="9.5" height="9.5" rx="1" fill="${cell}"/>
  <path d="M16 5v22M5 16h22" stroke="${rule}" stroke-width="2"/>
  <rect x="5" y="5" width="22" height="22" rx="1.5" fill="none" stroke="${rule}" stroke-width="2"/>
</svg>
`;
}

const OUTPUTS = [
  { path: join(ROOT, 'frontend', 'src', 'styles', 'tokens.css'), content: tokensCss() },
  { path: join(ROOT, 'frontend', 'src', 'app', 'icon.svg'), content: iconSvg() },
];

// ---------- run ----------

const stale = [];
for (const { path, content } of OUTPUTS) {
  const current = existsSync(path) ? readFileSync(path, 'utf8').replace(/\r\n/g, '\n') : null;
  if (current === content) continue;
  if (check) stale.push(relative(ROOT, path));
  else {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content, 'utf8');
    console.log(`wrote ${relative(ROOT, path)}`);
  }
}

if (failures.length) {
  console.error('Contrast failures (WCAG 2.2 AA):');
  for (const failure of failures) console.error(`  - ${failure}`);
}
if (stale.length) console.error(`Out of date (run node design/build-tokens.mjs): ${stale.join(', ')}`);
if (failures.length || stale.length) process.exitCode = 1;
else if (check) console.log('tokens: generated files current, all contrast pairs pass');
