// Builds every generated design file from design/tokens.json — the one source of Gridline's design language.
//   node design/build-tokens.mjs           write the generated files
//   node design/build-tokens.mjs --check   fail (exit 1) if any generated file is out of date or any contrast pair fails
// No dependencies: runs on plain Node from any working directory.
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const tokens = JSON.parse(readFileSync(join(HERE, 'tokens.json'), 'utf8'));
const check = process.argv.includes('--check');
const THEMES = ['light', 'dark'];
const HEADER = 'GENERATED by design/build-tokens.mjs from design/tokens.json. Do not edit by hand.';

// ---------- colour maths: OKLCH -> sRGB (Björn Ottosson's matrices), WCAG relative luminance ----------

function parseOklch(value) {
  const match = /^oklch\(\s*([\d.]+)\s+([\d.]+)\s+([\d.]+)\s*\)$/.exec(value);
  if (!match) throw new Error(`Not an oklch() colour: ${value}`);
  return { l: Number(match[1]), c: Number(match[2]), h: Number(match[3]) };
}

function oklchToLinearSrgb({ l, c, h }) {
  const a = c * Math.cos((h * Math.PI) / 180);
  const b = c * Math.sin((h * Math.PI) / 180);
  const l_ = (l + 0.3963377774 * a + 0.2158037573 * b) ** 3;
  const m_ = (l - 0.1055613458 * a - 0.0638541728 * b) ** 3;
  const s_ = (l - 0.0894841775 * a - 1.291485548 * b) ** 3;
  return [
    4.0767416621 * l_ - 3.3077115913 * m_ + 0.2309699292 * s_,
    -1.2684380046 * l_ + 2.6097574011 * m_ - 0.3413193965 * s_,
    -0.0041960863 * l_ - 0.7034186147 * m_ + 1.707614701 * s_,
  ].map((channel) => Math.min(1, Math.max(0, channel)));
}

const encode = (x) => (x <= 0.0031308 ? 12.92 * x : 1.055 * x ** (1 / 2.4) - 0.055);

export function oklchToHex(value) {
  return `#${oklchToLinearSrgb(parseOklch(value))
    .map((x) => Math.round(encode(x) * 255).toString(16).padStart(2, '0'))
    .join('')}`;
}

function luminance(value) {
  // WCAG uses luminance of the sRGB colour as displayed: gamut-clamp, 8-bit round, then linearise.
  const [r, g, b] = oklchToLinearSrgb(parseOklch(value)).map((x) => {
    const byte = Math.round(encode(x) * 255) / 255;
    return byte <= 0.04045 ? byte / 12.92 : ((byte + 0.055) / 1.055) ** 2.4;
  });
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

function contrast(foreground, background) {
  const [hi, lo] = [luminance(foreground), luminance(background)].sort((x, y) => y - x);
  return (hi + 0.05) / (lo + 0.05);
}

// ---------- the model ----------

const roles = Object.keys(tokens.color.light).filter((key) => !key.startsWith('$'));
for (const theme of THEMES) {
  const missing = roles.filter((role) => !tokens.color[theme][role]);
  const extra = Object.keys(tokens.color[theme]).filter((role) => !role.startsWith('$') && !roles.includes(role));
  if (missing.length || extra.length) {
    throw new Error(`Theme "${theme}" must define exactly the light roles. Missing: ${missing}. Extra: ${extra}.`);
  }
}
const colour = (theme, role) => tokens.color[theme][role].$value;
const entries = (group) => Object.entries(group).filter(([key]) => !key.startsWith('$'));

// ---------- contrast gate ----------

const MINIMUM = { text: 4.5, large: 3, ui: 3 };
const failures = [];
for (const theme of THEMES) {
  for (const [fg, bg, kind] of tokens.contrast.pairs) {
    const ratio = contrast(colour(theme, fg), colour(theme, bg));
    if (ratio < MINIMUM[kind]) failures.push(`${theme}: ${fg} on ${bg} = ${ratio.toFixed(2)} (needs ${MINIMUM[kind]} for ${kind})`);
  }
}

// ---------- outputs ----------

function tokensCss() {
  const vars = (theme) => roles.map((role) => `  --gl-${role}: ${colour(theme, role)};`).join('\n');
  const text = entries(tokens.text)
    .map(([name, t]) => `  --text-${name}: ${t.$value};\n  --text-${name}--line-height: ${t.leading};`)
    .join('\n');
  return `/* ${HEADER} */

:root,
[data-theme="light"] {
  color-scheme: light;
${vars('light')}
  --gl-shadow-overlay: ${tokens.shadow.overlay.light};
}

[data-theme="dark"] {
  color-scheme: dark;
${vars('dark')}
  --gl-shadow-overlay: ${tokens.shadow.overlay.dark};
}

@theme inline {
${roles.map((role) => `  --color-${role}: var(--gl-${role});`).join('\n')}

  --font-sans: ${tokens.font.sans.$value};
  --font-mono: ${tokens.font.mono.$value};
${entries(tokens.width).map(([name, w]) => `  --font-width-${name}: ${w.$value};`).join('\n')}

${text}

${entries(tokens.radius).map(([name, r]) => `  --radius-${name}: ${r.$value};`).join('\n')}

  --shadow-overlay: var(--gl-shadow-overlay);

${entries(tokens.motion)
  .map(([name, m]) => (name.startsWith('ease') ? `  --ease-${name.slice(5)}: ${m.$value};` : `  --duration-${name}: ${m.$value};`))
  .join('\n')}
}
`;
}

/**
 * The mark: an ink tile holding a 2x2 grid of label-stock cells; the top-right cell is the hi-vis inspection tag, with
 * its grommet hole punched. Same geometry as components/brand/logo.tsx (which takes its colours from the live theme).
 */
function iconSvg() {
  const tile = oklchToHex(colour('light', 'text'));
  const label = oklchToHex(colour('light', 'canvas'));
  const tag = oklchToHex(colour('light', 'tag'));
  return `<!-- ${HEADER} -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
  <rect width="32" height="32" rx="6" fill="${tile}"/>
  <rect x="5.5" y="5.5" width="9.5" height="9.5" rx="1.5" fill="${label}"/>
  <rect x="17" y="5.5" width="9.5" height="9.5" rx="1.5" fill="${tag}"/>
  <rect x="5.5" y="17" width="9.5" height="9.5" rx="1.5" fill="${label}"/>
  <rect x="17" y="17" width="9.5" height="9.5" rx="1.5" fill="${label}"/>
  <circle cx="21.75" cy="10.25" r="1.7" fill="${tile}"/>
</svg>
`;
}

/**
 * The Scalar API reference theme: the same tokens, as Scalar's own variables, for light and dark. Hex, not oklch, so the
 * reference renders the same in every browser Scalar supports. Reading mode: a quiet page, ink text, chrome-yellow actions.
 */
function scalarThemeTs() {
  const hex = (theme, role) => oklchToHex(colour(theme, role));
  const mode = (theme) => `
  --scalar-color-1: ${hex(theme, 'text')};
  --scalar-color-2: ${hex(theme, 'text-muted')};
  --scalar-color-3: ${hex(theme, 'text-subtle')};
  --scalar-color-accent: ${hex(theme, 'action')};
  --scalar-background-1: ${hex(theme, 'canvas')};
  --scalar-background-2: ${hex(theme, 'surface')};
  --scalar-background-3: ${hex(theme, 'sunken')};
  --scalar-background-accent: ${hex(theme, 'tag-soft')};
  --scalar-border-color: ${hex(theme, 'line')};
  --scalar-button-1: ${hex(theme, 'tag')};
  --scalar-button-1-hover: ${hex(theme, 'tag-hover')};
  --scalar-button-1-color: ${hex(theme, 'on-tag')};
  --scalar-color-green: ${hex(theme, 'pass')};
  --scalar-color-red: ${hex(theme, 'hold')};
  --scalar-color-orange: ${hex(theme, 'tab-orange')};
  --scalar-color-yellow: ${hex(theme, 'caution')};
  --scalar-color-blue: ${hex(theme, 'tab-blue')};
  --scalar-sidebar-background-1: ${hex(theme, 'canvas')};
  --scalar-sidebar-color-1: ${hex(theme, 'text')};
  --scalar-sidebar-color-2: ${hex(theme, 'text-muted')};
  --scalar-sidebar-item-hover-background: ${hex(theme, 'sunken')};
  --scalar-sidebar-item-active-background: ${hex(theme, 'tag-soft')};
  --scalar-sidebar-border-color: ${hex(theme, 'line')};
  --scalar-sidebar-search-background: ${hex(theme, 'surface')};
  --scalar-sidebar-search-border-color: ${hex(theme, 'line-strong')};
  --scalar-sidebar-search-color: ${hex(theme, 'text-subtle')};
  --scalar-scrollbar-color: ${hex(theme, 'line-strong')};
  --scalar-scrollbar-color-active: ${hex(theme, 'text-subtle')};`;

  const css = `@import url('https://fonts.googleapis.com/css2?family=Archivo:wdth,wght@62..125,100..900&family=EB+Garamond:wght@400..800&family=Martian+Mono:wght@100..800&display=swap');

:root {
  --scalar-font: 'Archivo', ui-sans-serif, system-ui, sans-serif;
  --scalar-font-code: 'Martian Mono', ui-monospace, monospace;
  --scalar-radius: 3px;
  --scalar-radius-lg: 4px;
  --scalar-radius-xl: 6px;
  --scalar-border-width: 1px;
}

.light-mode {${mode('light')}
}

.dark-mode {${mode('dark')}
}

/* Section titles are condensed, heavy and uppercase, like the site's headlines. */
h1,
h2 {
  font-variation-settings: 'wdth' 64;
  font-weight: 800;
  text-transform: uppercase;
  letter-spacing: -0.005em;
}

/*
 * The title block. The two pills that sat above the title are hidden, the title is much larger, and the version and
 * OpenAPI number come back as two stamps beneath it. Their text is added per request in scalar.ts, from the served
 * document, so it cannot go stale.
 */
.introduction-section .section-content > .flex.gap-1\\.5 {
  display: none;
}

.introduction-section .section-header {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: 0.75rem;
}

.introduction-section .section-header-label {
  order: 0;
  flex: 0 0 100%;
  margin: 0;
  font-size: clamp(3.5rem, 7vw, 6rem);
  line-height: 0.9;
}

.introduction-section .section-header::before,
.introduction-section .section-header::after {
  order: 1;
  padding: 0.35rem 0.6rem;
  border: 1px solid var(--scalar-color-1);
  border-radius: 2px;
  font-family: var(--scalar-font);
  font-size: 0.75rem;
  font-weight: 700;
  font-variation-settings: 'wdth' 72;
  letter-spacing: 0.08em;
  line-height: 1;
  text-transform: uppercase;
}

.introduction-section .section-header::before {
  background: var(--scalar-button-1);
  color: var(--scalar-button-1-color);
}

.introduction-section .section-header::after {
  background: var(--scalar-background-2);
  color: var(--scalar-color-1);
}

a {
  text-underline-offset: 0.2em;
}

::selection {
  background: ${hex('light', 'tag')};
  color: ${hex('light', 'on-tag')};
}`;

  return `// ${HEADER}
// The Scalar API reference theme (see scalar.ts). Colours and fonts come from design/tokens.json.
export const SCALAR_CUSTOM_CSS = ${JSON.stringify(css)};

/** The Gridline mark as a data URI, for the reference's browser tab. */
export const SCALAR_FAVICON = ${JSON.stringify(`data:image/svg+xml;base64,${Buffer.from(iconSvg()).toString('base64')}`)};
`;
}

const OUTPUTS = [
  { path: join(ROOT, 'frontend', 'src', 'styles', 'tokens.css'), content: tokensCss() },
  { path: join(ROOT, 'frontend', 'src', 'app', 'icon.svg'), content: iconSvg() },
  { path: join(ROOT, 'backend', 'src', 'docs', 'scalar-theme.ts'), content: scalarThemeTs() },
];

// ---------- run ----------

const stale = [];
for (const { path, content } of OUTPUTS) {
  const current = existsSync(path) ? readFileSync(path, 'utf8').replace(/\r\n/g, '\n') : null;
  if (current === content) continue;
  if (check) stale.push(relative(ROOT, path));
  else {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content, 'utf8');
    console.log(`wrote ${relative(ROOT, path)}`);
  }
}

if (failures.length) {
  console.error('Contrast failures (WCAG 2.2 AA):');
  for (const failure of failures) console.error(`  - ${failure}`);
}
if (stale.length) console.error(`Out of date (run node design/build-tokens.mjs): ${stale.join(', ')}`);
if (failures.length || stale.length) process.exitCode = 1;
else if (check) console.log('tokens: generated files current, all contrast pairs pass');
