import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';

/**
 * Project-2's worst documentation debt: most GETs returned raw Mongoose
 * documents with no response DTO, so their generated OpenAPI schemas came
 * out empty — and an empty schema is exactly what `openapi-typescript` turns
 * into `unknown` (or `Record<string, never>`) in the generated client types,
 * silently degrading the frontend's "typed" API client to `any`-shaped data
 * with no compiler warning anywhere.
 *
 * This reads the COMMITTED `docs/openapi.d.ts` (regenerated by
 * `npm run docs:types`, which `docs:check` — not this spec — keeps honest)
 * and asserts the probe response types are real, named shapes. It exists so
 * that regression shows up as a failing unit test, not as a silent `any`
 * three layers away in a frontend nobody's looking at yet.
 */
describe('generated OpenAPI types (docs/openapi.d.ts)', () => {
  const generatedTypes = readFileSync(
    join(process.cwd(), 'docs', 'openapi.d.ts'),
    'utf8',
  );

  function schemaBlockFor(schemaName: string): string {
    const marker = `${schemaName}: {`;
    const start = generatedTypes.indexOf(marker);
    expect(start, `schema "${schemaName}" not found in docs/openapi.d.ts`).toBeGreaterThanOrEqual(0);

    const braceOpen = start + marker.length - 1;
    let depth = 0;
    let end = braceOpen;
    for (let i = braceOpen; i < generatedTypes.length; i += 1) {
      if (generatedTypes[i] === '{') depth += 1;
      if (generatedTypes[i] === '}') {
        depth -= 1;
        if (depth === 0) {
          end = i;
          break;
        }
      }
    }

    return generatedTypes.slice(start, end + 1);
  }

  it.each(['ProbeEchoResponseDto', 'ProbeSortedResponseDto'])(
    '%s is not the empty-schema fallback (unknown / Record<string, never>)',
    (schemaName) => {
      const block = schemaBlockFor(schemaName);

      expect(block).not.toContain(': unknown');
      expect(block).not.toContain('Record<string, never>');
    },
  );

  it('ProbeEchoResponseDto carries its real, named properties', () => {
    const block = schemaBlockFor('ProbeEchoResponseDto');

    expect(block).toContain('n: number');
    expect(block).toContain('doubled: number');
    expect(block).toContain('correlationId?: string');
  });

  it('ProbeSortedResponseDto references the nested SortFieldDto by name', () => {
    const block = schemaBlockFor('ProbeSortedResponseDto');

    expect(block).toContain('SortFieldDto');
  });
});
